### ISSUE TITLE
Research on rendering geometries across vector tiles without artifacts

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/deck.gl#10]
Managing polygon (and lines) with our current TileLayer approach produces some rendering 'artifacts'.

The approach follows this sequence:
- MVT tile load
- tile decoding 
- conversion to GeoJSON, 
applied independently to every tile

There is no concept of 'merging' geometries for rendering, so those glitches are kind of expected.

This is an example, using polygons. Notice the cuts in the polygons, corresponding to tiles borders

![image](https://user-images.githubusercontent.com/458196/65534312-7277ee80-deff-11e9-8dca-abb052310f6d.png)

It is important to notice that this problem is pretty evident when rendering **polygons** but also applies to **lines** crossing tiles (although rendering problems could be not so obvious). And we also have to discard any possible 'artifact' regarding **points**.

**Comment by jesusbotella** [comment]
I've used QGIS to represent the tiles of the map above and here's what I got:
<img width="1140" alt="Screenshot 2019-09-25 at 11 33 31" src="https://user-images.githubusercontent.com/4319728/65589600-9d0e8980-df89-11e9-8e83-51eb216bd4f7.png">

Regarding the upper left part pictured in the screenshot, I believe that there's no buffer around the tiles because when hiding/showing the left/right tile there's no more colored area apart from the border of the polygon.

That tiles were downloaded right away from the tiles that the browser renders, so they may be affected by some of the parameters passed in map's instantiation.
